

### FOLLOWING IS THE MASTER LIST OF FIELD MAPPINGS

CADET_FIRST_NAME = "cadet_first_name"
CADET_SURNAME = "cadet_second_name"
CADET_DATE_OF_BIRTH = "cadet_date_of_birth"
PAYMENT_STATUS = "registration_payment_status"
REGISTRATION_DATE = "registration_date"
WEEKEND_DAYS_ATTENDING_INPUT = "weekend_days_attending_input"
ALL_DAYS_ATTENDING_INPUT = "all_days_attending_input"

REGISTERED_BY_FIRST_NAME = "registered_by_first_name"
REGISTERED_BY_LAST_NAME = "registered_by_last_name"
REGISTERED_EMAIL = "registered_by_email"
REGISTERED_PHONE = "registered_by_phone"

RESPONSIBLE_ADULT_NAME = "responsible_adult_name"
RESPONSIBLE_ADULT_NUMBER = "responsible_adult_number"

ANY_OTHER_INFORMATION = "any_other_information"

DESIRED_CLUB_BOAT = "desired_club_boat_if_available"
SWIM_25_METRES = "cadet_swim_25m"
CADET_BOUYANCY_AID = "cadet_bouyancy_aid"
CADET_OWN_BOAT = "cadet_own_boat_yes_or_no"
CADET_OWN_BOAT_CLASS = "cadet_own_boat_class"
CADET_OWN_BOAT_SAIL_NUMBER = "cadet_own_boat_sail_number"
CADET_DOUBLE_HANDED_PARTNER = "cadet_double_handed_partner"

CADET_T_SHIRT_SIZE = "cadet_t_shirt_size"
CADET_GROUP_PREFERENCE = "cadet_group_preference"
CADET_HIGHEST_QUALIFICATION = "cadet_highest_qualification"

TEMPORARY_MEMBERSHIPS_REQUIRED = "temporary_memberships_required"
TEMPORARY_MEMBERSHIP_NAMES = "temporary_membership_names"

FOOD_TICKET_ONE_DAY = "food_ticket_one_day"
FOOD_TICKET_TWO_DAYS ="food_ticket_two_days"
FOOD_TICKET_CHILD ="food_ticket_under16"
FOOD_TICKET_ADULT_NOT_VOLUNTEERING ="food_ticket_non_volunteer"
FOOD_TICKET_GALA_ONLY = "food_tickets_gala_dinner"

VOLUNTEER_STATUS = "volunteer_status"

VOLUNTEER1_AVAILABILITY = "volunteer1_availability_all_days"
VOLUNTEER1_WEEKEND_AVAILABILITY = "volunteer1_weekend_availability"
VOLUNTEER1_NAME = "volunteer1_name"
VOLUNTEER1_DUTIES = "volunteer1_duties"
VOLUNTEER1_SAME_OR_VARIED = "volunteer1_same_or_varied"
VOLUNTEER1_FOOD_PREFERENCE = "volunteer1_food_preference"

VOLUNTEER2_AVAILABILITY = "volunteer2_availability_all_days"
VOLUNTEER2_WEEKEND_AVAILABILITY = "volunteer2_weekend_availability"
VOLUNTEER2_NAME = "volunteer2_name"
VOLUNTEER2_DUTIES = "volunteer2_duties"
VOLUNTEER2_SAME_OR_VARIED = "volunteer2_same_or_varied"
VOLUNTEER2_FOOD_PREFERENCE = "volunteer2_food_preference"

REGISTRATION_TOTAL_FEE = "registration_total_fee"
REGISTRATION_INTERNAL_NOTES = "registration_internal_notes"
REGISTERED_BY_MEMBER = "registered_by_member"

CADET_FOOD_PREFERENCE = "cadet_food_preference"

ALL_FIELDS_EXPECTED_IN_WA_FILE_MAPPING = [
    CADET_FIRST_NAME,
CADET_SURNAME,
CADET_DATE_OF_BIRTH,
PAYMENT_STATUS,
REGISTRATION_DATE,
WEEKEND_DAYS_ATTENDING_INPUT,
ALL_DAYS_ATTENDING_INPUT,
CADET_FOOD_PREFERENCE,
RESPONSIBLE_ADULT_NAME,
    RESPONSIBLE_ADULT_NUMBER,

REGISTERED_BY_FIRST_NAME,
    REGISTERED_BY_LAST_NAME,
    REGISTERED_EMAIL,
    REGISTERED_PHONE,
REGISTRATION_INTERNAL_NOTES,
    REGISTERED_BY_MEMBER,

ANY_OTHER_INFORMATION,

VOLUNTEER_STATUS,

VOLUNTEER1_AVAILABILITY,
VOLUNTEER1_WEEKEND_AVAILABILITY,
VOLUNTEER1_NAME,
VOLUNTEER1_DUTIES,
VOLUNTEER1_SAME_OR_VARIED,
VOLUNTEER1_FOOD_PREFERENCE,

VOLUNTEER2_AVAILABILITY,
VOLUNTEER2_WEEKEND_AVAILABILITY,
VOLUNTEER2_NAME,
VOLUNTEER2_DUTIES,
VOLUNTEER2_SAME_OR_VARIED,
VOLUNTEER2_FOOD_PREFERENCE,
    REGISTRATION_TOTAL_FEE
]

#### FIXME CHECK ALL REQUIRED

## following are derived fields, not found in WA data
CADET_NAME = "Cadet" #### FIXME USED IN REPORTING DELETE
GROUP_STR_NAME = "group"#### FIXME USED IN REPORTING DELETE

### THIS MUST BE ACCURATE OR WA FILE IN/OUT WILL FAIL
FIELDS_WITH_DATES = [CADET_DATE_OF_BIRTH]
FIELDS_WITH_DATETIMES = [REGISTRATION_DATE]
FIELDS_WITH_INTEGERS = []
FIELDS_AS_STR = [RESPONSIBLE_ADULT_NUMBER] ## Only fields where resolving as natural field would cause problems


## Editable/non editable in registration data page

## VIEW ONLY
## Rule of thumb is we do all editing in skipperman, not WA
## don't include everything just what is required for information purposes
FIELDS_VIEW_ONLY_IN_EDIT_VIEW = [
    ANY_OTHER_INFORMATION,
    CADET_FOOD_PREFERENCE,
    REGISTRATION_DATE,
    PAYMENT_STATUS, REGISTRATION_TOTAL_FEE,
    REGISTERED_BY_FIRST_NAME,
    REGISTERED_BY_LAST_NAME,
    REGISTERED_EMAIL,
    REGISTERED_PHONE,
    REGISTRATION_INTERNAL_NOTES

]

FIELDS_TO_EDIT_IN_EDIT_VIEW = [ ## excludes status, days attending, food preference since these are added afterwards
    RESPONSIBLE_ADULT_NAME,
    RESPONSIBLE_ADULT_NUMBER,
    ]


## VOLUNTEER GROUPINGS
NAME_KEY_IN_VOLUNTEER_FIELDS_DICT = "VOLUNTEER_NAME"
AVAILABILITY_KEY_IN_VOLUNTEER_FIELDS_DICT= 'AVAILABILITY'
WEEKEND_AVAILABILITY_KEY_IN_VOLUNTEER_FIELDS_DICT = 'WEEKEND_AVAILABILITY'
DUTIES_KEY_IN_VOLUNTEER_FIELDS_DICT = 'DUTIES'
SAME_OR_VARIED_KEY_IN_VOLUNTEER_FIELDS_DICT= 'SAME_OR_VARIED'
FOOD_PREFERENCE_KEY_IN_VOLUNTEER_FIELDS_DICT = 'FOOD_PREFERENCE'

LIST_OF_VOLUNTEER_FIELDS = [
    {
        ## First volunteer
AVAILABILITY_KEY_IN_VOLUNTEER_FIELDS_DICT : VOLUNTEER1_AVAILABILITY,
WEEKEND_AVAILABILITY_KEY_IN_VOLUNTEER_FIELDS_DICT : VOLUNTEER1_WEEKEND_AVAILABILITY,
NAME_KEY_IN_VOLUNTEER_FIELDS_DICT : VOLUNTEER1_NAME,
DUTIES_KEY_IN_VOLUNTEER_FIELDS_DICT: VOLUNTEER1_DUTIES,
SAME_OR_VARIED_KEY_IN_VOLUNTEER_FIELDS_DICT : VOLUNTEER1_SAME_OR_VARIED,
FOOD_PREFERENCE_KEY_IN_VOLUNTEER_FIELDS_DICT: VOLUNTEER1_FOOD_PREFERENCE},

{
    ## Second volunteer
AVAILABILITY_KEY_IN_VOLUNTEER_FIELDS_DICT : VOLUNTEER2_AVAILABILITY,
WEEKEND_AVAILABILITY_KEY_IN_VOLUNTEER_FIELDS_DICT : VOLUNTEER2_WEEKEND_AVAILABILITY,
NAME_KEY_IN_VOLUNTEER_FIELDS_DICT : VOLUNTEER2_NAME,
DUTIES_KEY_IN_VOLUNTEER_FIELDS_DICT: VOLUNTEER2_DUTIES,
SAME_OR_VARIED_KEY_IN_VOLUNTEER_FIELDS_DICT : VOLUNTEER2_SAME_OR_VARIED,
FOOD_PREFERENCE_KEY_IN_VOLUNTEER_FIELDS_DICT: VOLUNTEER2_FOOD_PREFERENCE},

]