### FOLLOWING IS THE MASTER LIST OF FIELD MAPPINGS

CADET_FIRST_NAME = "cadet_first_name"
CADET_SURNAME = "cadet_second_name"
CADET_DATE_OF_BIRTH = "cadet_date_of_birth"
PAYMENT_STATUS = "registration_payment_status"
REGISTRATION_DATE = "registration_date"

### THIS MUST BE ACCURATE OR FILE IN/OUT WILL FAIL
FIELDS_WITH_DATES = [CADET_DATE_OF_BIRTH]
FIELDS_WITH_DATETIMES = [REGISTRATION_DATE]
FIELDS_WITH_INTEGERS = []

SPECIAL_FIELDS = [PAYMENT_STATUS]

FIELDS_TO_IGNORE_WHEN_COMPARING_WA_DIFF = [
    CADET_SURNAME, CADET_FIRST_NAME, CADET_DATE_OF_BIRTH,
    PAYMENT_STATUS, REGISTRATION_DATE
]