sudo: false
language: python

matrix:
  include:
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36

install:
  - pip install tox

script:
  - tox -e "${TOX_ENV}"

after_success:
  - coverage combine
  - codecov
