### FOLLOWING IS THE MASTER LIST OF FIELD MAPPINGS

CADET_FIRST_NAME = "cadet_first_name"
CADET_SURNAME = "cadet_second_name"
CADET_DATE_OF_BIRTH = "cadet_date_of_birth"
PAYMENT_STATUS = "registration_payment_status"
REGISTRATION_DATE = "registration_date"

### THIS MUST BE ACCURATE OR FILE IN/OUT WILL FAIL
FIELDS_WITH_DATES = [CADET_DATE_OF_BIRTH]
FIELDS_WITH_DATETIMES = [REGISTRATION_DATE]