ADD_VOLUNTEER_BUTTON_LABEL = "Add volunteer"
CHECK_BUTTON_LABEL = "Check details entered"
FINAL_ADD_BUTTON_LABEL = "Yes - these details are correct - add this volunteer"
DELETE_BUTTON_LABEL = "Delete volunteer"
EDIT_BUTTON_LABEL = "Edit volunteer name and skills"
BACK_BUTTON_LABEL = "Back"
CANCEL_BUTTON_LABEL = "Cancel"
SURE_DELETE_BUTTON_LABEL = "I am sure - delete this volunteer"
SAVE_BUTTON_LABEL = "Save"
EDIT_CADET_CONNECTIONS_BUTTON_LABEL = "Add/modify connections to cadets"
ADD_CONNECTION_BUTTON_LABEL = "Add connection"
DELETE_CONNECTION_BUTTON_LABEL = "Delete connection"


VOLUNTEER = "volunteer"
FIRST_NAME = "first_name"
SURNAME = "surname"
SKILLS = "skills"
CONNECTION = "connection"
