### DEFINITION OF MENUS USING A NESTED DICT
### TOP LEVEL DICT IS LIST OF SUBMENUS
### NEXT LEVEL DICT KEYS ARE SUBMENU OPTIONS
### NEXT LEVEL DICT VALUES ARE NAMES OF METHODS TO CALL IN web/actions

